### ISSUE TITLE
Remove "descending" photo order photo connection and replace with alphabetical order

### ISSUE THREAD

**Issue by himynamesdave** [trekview/tourer#1]
Most photos are taken in ascending time order, e.g. 0:01, 0:02... We currently support connections in ascending and descending time order.

There are very few times descending time order is needed and this is confusing to users. We should remove this option (https://github.com/trekview/tourer/blob/v.0.2-gui/trekview.py#L235)

Instead, to allow users to manipulate photo connections (by file renaming) we should allow user option to upload in filename ascending order (A-Z).

User will be asked: 

Do you want to connect photos in ascending time order (recommended) [T], ascending alphabetical order [A], or no connection to be made [N]? If no selected, Google will automatically attempt to link your photos if they are no more than 5 meters apart')

**Comment by annndrey** [comment]
Fixed in 169170c466a3f10eb965f2b74a9ea1ff5b23c5e5
