### ISSUE TITLE
Should introduce same tour / photo DB structure as Explorer

### ISSUE THREAD

**Issue by himynamesdave** [trekview/tourer#10]
Explorer should hold the same data as Tourer stores locally.

We need to update Tourer to store following data in tables locally to support this:

Tour table

- tourer_tour_id: [optional] [tourer will send local id] [Max 10 chars]
- tour_ name: [required] [Max 70 chars]
- description: [optional] [Max 140 chars]
- tour_tags: [optional] [list of single word tags, comma separated] [Max 240 chars]
- tour_type: [required] [see issue #2]
- tour_transport_type: [required] [see issue #2]

Photo table

- tourer_photo_id: [optional] [tourer will send local id] [Max 10 chars]
- photo_filename: ”MULTISHOT_0989_00001.jpg” [MAX 50 chars] [REQUIRED]
- photo_datetime: 2019-07-01 00:00:01 [MUST BE DATE TIME] [REQUIRED]
- photo_latitude: -22.516189 [MUST BE NUMBER MAX 20 CHARS] [REQUIRED]
- photo_longitude: 45.5330688 [MUST BE NUMBER MAX 20 CHARS] [REQUIRED]
- photo_country: [2 digit ISO country code] [MAX 2 CHARS] [REQUIRED]
- photo_elevation_meters: 300 [MUST BE NUMBER MAX 6 CHARS] [OPTIONAL]
- photo_heading: 258.22 [MUST BE NUMBER MAX 20 CHARS] [OPTIONAL]
- street_view_thumbnail_url: [MUST BE URL MAX 500 CHARS] [REQUIRED]
- street_view_url: [MUST BE URL MAX 500 CHARS] [REQUIRED]
- photo_conntection: ”PHOTO-j89j477fh-000002” [MUST BE CHARACTERS MAX 70 CHARS] [OPTIONAL]
- photo_conntection_distance_km: 0.05 [MUST BE NUMBER MAX 6 CHARS] [OPTIONAL]

Linked to: https://github.com/trekview/explorer/issues/4

**Comment by annndrey** [comment]
Added in b452ff4
