### ISSUE TITLE
Add ability for users to group tours as tourbooks

### ISSUE THREAD

**Issue by himynamesdave** [trekview/tourer#19]
A Tourbook is a collection of tours.

For example, user might create tourbook of "mountain tours".

Tourbook should have:

- ID (fixed on creation)
- Name (modifiable at any time by user, unique for user)
- Description (modifiable at any time by user)
- Tours (modifiable at any time by user)

Tourbooks can have 0 more photos attached to them

User can only add existing tours in Tourer to tourbook.

If Explorer API key set, sync info with Explorer API. Related Explorer ticket: https://github.com/trekview/explorer/issues/10

**Comment by annndrey** [comment]
It would be useful to have a tourer_tourbook_id to have tourer & explorer API synced. Now, without a reference field it's unclear how to link together local  & remote tourbooks. 

We can still have a one-way sync, when we first create a local tourbook then create an Expoorer tourbook and add an Expoorer tourbook ID to our local database.
