### ISSUE TITLE
Add country geo lookup function to calculate country of photo

### ISSUE THREAD

**Issue by himynamesdave** [trekview/tourer#2]
Use the Google geocoding API to keep a local copy of photo country.

https://developers.google.com/maps/documentation/geocoding/start?csw=1

Add 2 letter country ISO code to photo record: https://www.nationsonline.org/oneworld/country_code_list.htm

Add to docs: User will need to enable geocode API in their Google account.

**Comment by annndrey** [comment]
Hmm, looks like I've linked the wrong issue number in the commit above.

**Comment by annndrey** [comment]
For geocoding tasks there's already a Python lib, https://pypi.org/project/geopy/, including Google Geocoding API & OpenStreetMap Nominatim. The second one is more useful, as long as the only data we need is the country code. There's no limits to API calls number etc, like the Google API usually have.

**Comment by annndrey** [comment]
Added ISO country code support for both GUI & CLI, 07b30a4a8563b6f65839780470561e4140338073
