### ISSUE TITLE
Update StreetView fields stored against each photo record

### ISSUE THREAD

**Issue by himynamesdave** [trekview/tourer#28]
We currently collect downloadurl from Streetview response. However, this is not perfect as this should be private to user (or user who is authenticated). To do this requires API key, thus costs money.

Can we capture the following NEW fields against photo record returned by streetview:

https://developers.google.com/streetview/publish/reference/rest/v1/photo

- SV photoid (new -- should be submitted to Explorer streetview_photoid field)
- SV downloadurl (maybe rename?)
- SV shareLink (new -- should be submitted to Explorer instead of download url)

_Note, this does not cover all streetview fields we already collect (like thumbnailUrl, publish status). These should remain unchanged_

**Comment by annndrey** [comment]
Fixed in 4966c50b61163dfc1d629f2f3d01cafa056bf908
