### ISSUE TITLE
If user selects to connect photos, add heading information to local record and submit to Street View

### ISSUE THREAD

**Issue by himynamesdave** [trekview/tourer#3]
The app allows users to link photos together (connections).

In Street View this can be visualised as the blue line. Photos that are connected have blue line.

Some photos contain XMP with heading. Many do not. 

We should offer a raw heading calculation to orientate photo correctly.

On upload of photos (if connection = true) user should see message:

"Do you want to Tourer to calculate photo heading (direction)? This is recommended if the connected photos have a clear line of sight between them."

If true,

This data should be sent to Street View and stored locally.

https://developers.google.com/streetview/publish/reference/rest/v1/photo#Pose

Here are some examples of how to calculate heading: https://www.movable-type.co.uk/scripts/latlong.html

https://pypi.org/project/geo-py/

Because our users upload photos (typically) with 5m distance between each, we should not make this calculation complex.

**Comment by annndrey** [comment]
Added heading calculation in case of manual connection method is selected 11e4498afe06001421b99a758cc6e2406ac9cca9

**Comment by annndrey** [comment]
Added heading column to te database, ef9dcf9a88961af03d2f7bb393ee7ac7cdceb844
