### ISSUE TITLE
Database should store camera make and model

### ISSUE THREAD

**Issue by himynamesdave** [trekview/tourer#30]
Explorer uses camera make and camera model fields (e.g GoPro // Fusion)

```
"camera_make": "Sony",
" camera_model": "MKX"
```

We should store both these values in photo table in Tourer, and sync with Explorer.

Currently photos table in Tourer photo table:

https://github.com/trekview/tourer/wiki/7-Database#photos-table

**Comment by annndrey** [comment]
Added in 286b3d5ef2f2a2d3af6a25e407a9f9a818d83097
