### ISSUE TITLE
photo.tourer_photo_id AND photo.photo_ID are duplicate records

### ISSUE THREAD

**Issue by himynamesdave** [trekview/tourer#39]
tourer_photo_id AND  photo_ID are duplicates. Should only have single `photo_id` record against photo.

https://docs.google.com/spreadsheets/d/1s5zWX0uhY6iPS4s2xJcOpohiGLPYunkpA94E3Nd5rjk/edit#gid=1721238466

This value should be synced with Explorer (and is recorded in Explorer as tourer_photo_id)

**Comment by annndrey** [comment]
`photo_id = Column(Integer, primary_key=True)
  tourer_photo_id = Column(String(10), nullable=True, unique=True)
`
Not sure that they're duplicates. The `photo_id` is the internal primary key, the `tourer_photo_id` is the random string that we send to Explorer API
