### ISSUE TITLE
If user selects to connect photos, add distance information to record

### ISSUE THREAD

**Issue by himynamesdave** [trekview/tourer#4]
If user chooses to make photo connections we should calculate distance (km) between photos and store against record as "distance to connected photo km".

https://pypi.org/project/geo-py/

This data should be stored against the photo locally.

**Comment by annndrey** [comment]
Added distance calculation between two neighbour photos for manual photo connection method, modified DB structure respectively, f6916242e837a5206b786da8f0e49f27f3098798
