### ISSUE TITLE
tour.tourer_tour_id AND tour.tour_ID are duplicate records

### ISSUE THREAD

**Issue by himynamesdave** [trekview/tourer#46]
`tourer_tour_id AND `tour`_ID` are duplicates. Should only have single `tour_id` record against tour.

https://docs.google.com/spreadsheets/d/1s5zWX0uhY6iPS4s2xJcOpohiGLPYunkpA94E3Nd5rjk/edit#gid=0

This value should be synced with Explorer (and is recorded in Explorer as tourer_tour_id)

**Comment by annndrey** [comment]
This is the same as for photos. 

`
tour_id = Column(Integer, primary_key=True)
tourer_tour_id = Column(String(10), nullable=False, unique=True)
`
`tour_id` is a primary key, tourer_tour_id is an unique string to identify the tour in the Explorer API
