### ISSUE TITLE
need to add photo.explorer_photo_id_field

### ISSUE THREAD

**Issue by himynamesdave** [trekview/tourer#47]
We do not currently log the photo id from explorer.

This is vital to make future api requests to Explorer for photo.

https://docs.google.com/spreadsheets/d/1s5zWX0uhY6iPS4s2xJcOpohiGLPYunkpA94E3Nd5rjk/edit#gid=1721238466

Need to add photo.explorer_photo_id_field

**Comment by annndrey** [comment]
Already done
