### ISSUE TITLE
Add support for users to sync tours with Explorer

### ISSUE THREAD

**Issue by himynamesdave** [trekview/tourer#6]
**Context**

Explorer is a web app (work in progress) that has been designed for Tourer.

https://explorer.trekview.org/

Photos uploaded to Street View (and local meta-data stored in Tourer) is interesting.

It is hard for users to share tours they have uploaded to Street View. They can only share individual URLs of photos. Photos also are not easily searchable (e.g I can't search tours on the water, created by a boat, in the UK, etc.)

Explorer offers a public search interface to do this.

Users can create tours on Explorer using the Explorer API (designed specifically for use with Tourer).

When user signs up for Explorer, they are given an API key: https://explorer.trekview.org/

**Requirement**

We need offer users the ability to share their tour uploaded to Street View in Tourer to Explorer.

![v3 diagrams](https://user-images.githubusercontent.com/1296409/62925572-8847af00-bdaa-11e9-91da-a717ab9598f1.jpg)

![v3 diagrams (1)](https://user-images.githubusercontent.com/1296409/62654550-ec581680-b957-11e9-92bd-c6336fd18984.jpg)

User should be able to enter their Explorer API key.

If API key exists tours / photo meta should be automatically synced with tourer. If no Explorer APi key show user message: "No Explorer API key exists. Your photos will not be synced to Explorer. Get you Explorer API key here: https://explorer.trekview.org

Creating tours on tourer is done in two parts:

- Create tour (and get tour id)
- Add photos to tour (using tour ID)

The API supports GET, PATCH and DELETE requests: https://github.com/trekview/explorer/wiki/API-Endpoints

If user updates / deletes photos / tours in Tourer these changes should be made to Explorer API.

Users should also be able to retrospectively sync tours with Explorer. For example, if user adds valid API key after adding tour, all tours that exist will be synced to explorer.

**Comment by annndrey** [comment]
Working, both CLI & GUI versions tested, 
0ee05d611b3377379a0c7f71dfebb641b7377b9e
