### ISSUE TITLE
Allow users to configure required setup info in CLI / UI

### ISSUE THREAD

**Issue by himynamesdave** [trekview/tourer#7]
Users should be able to add following in app:

- Google App API key
- Google App APi secret
- Explorer API key

Users can run this as CLI script "setup", or set these in app under "settings" page.

**Comment by himynamesdave** [comment]
Also related to #21

**Comment by annndrey** [comment]
Working for CLI version

**Comment by annndrey** [comment]
Would add the GUI config soon

**Comment by annndrey** [comment]
Now API keys setup works for both CLI & GUI
